import{S as v,i,a as m}from"./assets/vendor-c145bea9.js";(function(){const o=document.createElement("link").relList;if(o&&o.supports&&o.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))l(e);new MutationObserver(e=>{for(const s of e)if(s.type==="childList")for(const y of s.addedNodes)y.tagName==="LINK"&&y.rel==="modulepreload"&&l(y)}).observe(document,{childList:!0,subtree:!0});function t(e){const s={};return e.integrity&&(s.integrity=e.integrity),e.referrerpolicy&&(s.referrerPolicy=e.referrerpolicy),e.crossorigin==="use-credentials"?s.credentials="include":e.crossorigin==="anonymous"?s.credentials="omit":s.credentials="same-origin",s}function l(e){if(e.ep)return;e.ep=!0;const s=t(e);fetch(e.href,s)}})();const L=document.querySelector(".form"),c=document.querySelector(".gallery");document.querySelector(".gallery-box");const a=document.querySelector(".loader-top"),f=document.querySelector(".loader-bottom");document.querySelector("input");const n=document.querySelector(".load-image");let d=1,p=40,u="";const g=new v(".gallery a",{nav:!0,captionDelay:250,captionsData:"alt",close:!0,enableKeyboard:!0,docClose:!0});L.addEventListener("submit",S);n.addEventListener("click",q);function h(r,o){return m.defaults.baseURL="https://pixabay.com",m.get("/api/",{params:{key:"41901315-991c01eb87449dbd0d544d02b",q:r,image_type:"photo",orientation:"horizontal",safesearch:!0,page:o,per_page:p}})}function b(r=[]){return r.reduce((o,t)=>o+`<li class="gallery-item">
                          <a href=${t.largeImageURL}> 
                            <img class="gallery-img" src =${t.webformatURL} alt=${t.tags}/>
                          </a>
                          <div class="gallery-text-box">
                            <p>Likes: <span class="text-value">${t.likes}</span></p>
                            <p>views: <span class="text-value">${t.views}</span></p>
                            <p>comments: <span class="text-value">${t.comments}</span></p>
                            <p>downloads: <span class="text-value">${t.downloads}</span></p>
                        </div>
                        </li>`,"")}async function S(r){if(r.preventDefault(),a.style.display="block",n.style.display="none",u=r.target.elements.search.value.trim(),!u){c.innerHTML="",i.info({position:"topRight",message:"Error enter any symbols"}),a.style.display="none";return}try{const{data:{hits:o,totalHits:t}}=await h(u,d);o.length>0?(a.style.display="none",c.innerHTML=b(o),g.refresh(),i.success({position:"topRight",message:`We found ${t} photos`}),n.style.display="block"):(c.innerHTML="",i.error({position:"topRight",message:"Sorry, there are no images matching your search query. Please try again!"})),t<=p&&(n.style.display="none")}catch(o){console.log(o)}finally{a.style.display="none",r.target.reset()}}async function q(r){f.style.display="block",n.style.display="none";const t=document.querySelector(".gallery-item:first-child").getBoundingClientRect().height;try{d+=1;const{data:{hits:l,totalHits:e}}=await h(u,d),s=Math.ceil(e/p);if(n.style.display="block",c.insertAdjacentHTML("beforeend",b(l)),g.refresh(),d===s)return n.style.display="none",i.info({position:"topRight",message:"We're sorry, but you've reached the end of search results."})}catch(l){console.log(l)}finally{f.style.display="none",window.scrollBy({top:2*t,behavior:"smooth"})}}
//# sourceMappingURL=commonHelpers.js.map
